.TH "dataReader" 3 "Thu Jul 13 2017" "Version 1.0" "MOrepo converter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dataReader
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetInputFile\fP (std::string &inputFile)"
.br
.ti -1c
.RI "void \fBRun\fP ()"
.br
.ti -1c
.RI "double \fBgetExecutionTime\fP ()"
.br
.ti -1c
.RI "int \fBgetFrontSize\fP ()"
.br
.ti -1c
.RI "std::vector< std::vector< double > > \fBgetPoints\fP ()"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "std::vector< std::vector< double > > \fBpoints\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for MOrepo converter from the source code\&.
